%% Based on canonical data version 1.2.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/roman-numerals/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(roman_numerals_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").

'1_convert_1_test'() ->
    ?assertEqual("I", roman_numerals:roman(1)).

'2_convert_2_test'() ->
    ?assertEqual("II", roman_numerals:roman(2)).

'3_convert_3_test'() ->
    ?assertEqual("III", roman_numerals:roman(3)).

'4_convert_4_test'() ->
    ?assertEqual("IV", roman_numerals:roman(4)).

'5_convert_5_test'() ->
    ?assertEqual("V", roman_numerals:roman(5)).

'6_convert_6_test'() ->
    ?assertEqual("VI", roman_numerals:roman(6)).

'7_convert_9_test'() ->
    ?assertEqual("IX", roman_numerals:roman(9)).

'8_convert_27_test'() ->
    ?assertEqual("XXVII", roman_numerals:roman(27)).

'9_convert_48_test'() ->
    ?assertEqual("XLVIII", roman_numerals:roman(48)).

'10_convert_49_test'() ->
    ?assertEqual("XLIX", roman_numerals:roman(49)).

'11_convert_59_test'() ->
    ?assertEqual("LIX", roman_numerals:roman(59)).

'12_convert_93_test'() ->
    ?assertEqual("XCIII", roman_numerals:roman(93)).

'13_convert_141_test'() ->
    ?assertEqual("CXLI", roman_numerals:roman(141)).

'14_convert_163_test'() ->
    ?assertEqual("CLXIII", roman_numerals:roman(163)).

'15_convert_402_test'() ->
    ?assertEqual("CDII", roman_numerals:roman(402)).

'16_convert_575_test'() ->
    ?assertEqual("DLXXV", roman_numerals:roman(575)).

'17_convert_911_test'() ->
    ?assertEqual("CMXI", roman_numerals:roman(911)).

'18_convert_1024_test'() ->
    ?assertEqual("MXXIV", roman_numerals:roman(1024)).

'19_convert_3000_test'() ->
    ?assertEqual("MMM", roman_numerals:roman(3000)).

'1b_convert_1_test'() ->
    ?assertEqual(1, roman_numerals:fromRoman("I")).

'2b_convert_2_test'() ->
    ?assertEqual(2, roman_numerals:fromRoman("II")).

'3b_convert_3_test'() ->
    ?assertEqual(3, roman_numerals:fromRoman("III")).

'4b_convert_4_test'() ->
    ?assertEqual(4, roman_numerals:fromRoman("IV")).

'5b_convert_5_test'() ->
    ?assertEqual(5, roman_numerals:fromRoman("V")).

'6b_convert_6_test'() ->
    ?assertEqual(6, roman_numerals:fromRoman("VI")).

'7b_convert_9_test'() ->
    ?assertEqual(9, roman_numerals:fromRoman("IX")).

'8b_convert_27_test'() ->
    ?assertEqual(27, roman_numerals:fromRoman("XXVII")).

'9b_convert_48_test'() ->
    ?assertEqual(48, roman_numerals:fromRoman("XLVIII")).

'10b_convert_49_test'() ->
    ?assertEqual(49, roman_numerals:fromRoman("XLIX")).

'11b_convert_59_test'() ->
    ?assertEqual(59, roman_numerals:fromRoman("LIX")).

'12b_convert_93_test'() ->
    ?assertEqual(93, roman_numerals:fromRoman("XCIII")).

'13b_convert_141_test'() ->
    ?assertEqual(141, roman_numerals:fromRoman("CXLI")).

'14b_convert_163_test'() ->
    ?assertEqual(163, roman_numerals:fromRoman("CLXIII")).

'15b_convert_402_test'() ->
    ?assertEqual(402, roman_numerals:fromRoman("CDII")).

'16b_convert_575_test'() ->
    ?assertEqual(575, roman_numerals:fromRoman("DLXXV")).

'17b_convert_911_test'() ->
    ?assertEqual(911, roman_numerals:fromRoman("CMXI")).

'18b_convert_1024_test'() ->
    ?assertEqual(1024, roman_numerals:fromRoman("MXXIV")).

'19b_convert_3000_test'() ->
    ?assertEqual(3000, roman_numerals:fromRoman("MMM")).
